-- MySQL Script generated by MySQL Workbench
-- Mon Apr 13 22:23:58 2026
-- Model: New Model    Version: 1.0
-- MySQL Workbench Forward Engineering

SET @OLD_UNIQUE_CHECKS=@@UNIQUE_CHECKS, UNIQUE_CHECKS=0;
SET @OLD_FOREIGN_KEY_CHECKS=@@FOREIGN_KEY_CHECKS, FOREIGN_KEY_CHECKS=0;
SET @OLD_SQL_MODE=@@SQL_MODE, SQL_MODE='ONLY_FULL_GROUP_BY,STRICT_TRANS_TABLES,NO_ZERO_IN_DATE,NO_ZERO_DATE,ERROR_FOR_DIVISION_BY_ZERO,NO_ENGINE_SUBSTITUTION';

-- -----------------------------------------------------
-- Schema mydb
-- -----------------------------------------------------
-- -----------------------------------------------------
-- Schema comic_reader_db
-- -----------------------------------------------------

-- -----------------------------------------------------
-- Schema comic_reader_db
-- -----------------------------------------------------
CREATE SCHEMA IF NOT EXISTS `comic_reader_db` DEFAULT CHARACTER SET utf8mb4 COLLATE utf8mb4_unicode_ci ;
USE `comic_reader_db` ;

-- -----------------------------------------------------
-- Table `comic_reader_db`.`comics`
-- -----------------------------------------------------
CREATE TABLE IF NOT EXISTS `comic_reader_db`.`comics` (
  `comic_id` INT NOT NULL AUTO_INCREMENT,
  `title` VARCHAR(255) CHARACTER SET 'utf8mb4' COLLATE 'utf8mb4_0900_ai_ci' NOT NULL,
  `author` VARCHAR(100) CHARACTER SET 'utf8mb4' COLLATE 'utf8mb4_0900_ai_ci' NULL DEFAULT NULL,
  `description` TEXT NULL DEFAULT NULL,
  `cover_image` VARCHAR(500) NULL DEFAULT NULL,
  `status` VARCHAR(255) NULL DEFAULT NULL,
  `total_views` INT NULL DEFAULT '0',
  `total_follows` INT NULL DEFAULT '0',
  `created_at` TIMESTAMP NULL DEFAULT CURRENT_TIMESTAMP,
  `updated_at` TIMESTAMP NULL DEFAULT CURRENT_TIMESTAMP ON UPDATE CURRENT_TIMESTAMP,
  `last_chapter_at` DATETIME(6) NULL DEFAULT NULL,
  PRIMARY KEY (`comic_id`))
ENGINE = InnoDB
AUTO_INCREMENT = 54
DEFAULT CHARACTER SET = utf8mb4
COLLATE = utf8mb4_unicode_ci;


-- -----------------------------------------------------
-- Table `comic_reader_db`.`chapters`
-- -----------------------------------------------------
CREATE TABLE IF NOT EXISTS `comic_reader_db`.`chapters` (
  `chapter_id` INT NOT NULL AUTO_INCREMENT,
  `comic_id` INT NOT NULL,
  `chapter_number` DECIMAL(5,2) NOT NULL,
  `title` VARCHAR(255) CHARACTER SET 'utf8mb4' COLLATE 'utf8mb4_0900_ai_ci' NULL DEFAULT NULL,
  `views` INT NULL DEFAULT '0',
  `created_at` TIMESTAMP NULL DEFAULT CURRENT_TIMESTAMP,
  `updated_at` TIMESTAMP NULL DEFAULT CURRENT_TIMESTAMP ON UPDATE CURRENT_TIMESTAMP,
  `image_paths` JSON NULL DEFAULT NULL,
  `require_login` TINYINT(1) NOT NULL DEFAULT '0',
  PRIMARY KEY (`chapter_id`),
  UNIQUE INDEX `uniq_comic_chapter` (`comic_id` ASC, `chapter_number` ASC) VISIBLE,
  CONSTRAINT `chapters_ibfk_1`
    FOREIGN KEY (`comic_id`)
    REFERENCES `comic_reader_db`.`comics` (`comic_id`)
    ON DELETE CASCADE)
ENGINE = InnoDB
AUTO_INCREMENT = 60
DEFAULT CHARACTER SET = utf8mb4
COLLATE = utf8mb4_unicode_ci;


-- -----------------------------------------------------
-- Table `comic_reader_db`.`genres`
-- -----------------------------------------------------
CREATE TABLE IF NOT EXISTS `comic_reader_db`.`genres` (
  `genre_id` INT NOT NULL AUTO_INCREMENT,
  `name` VARCHAR(100) CHARACTER SET 'utf8mb4' COLLATE 'utf8mb4_0900_ai_ci' NOT NULL,
  `description` TEXT NULL DEFAULT NULL,
  PRIMARY KEY (`genre_id`),
  UNIQUE INDEX `name` (`name` ASC) VISIBLE)
ENGINE = InnoDB
AUTO_INCREMENT = 87
DEFAULT CHARACTER SET = utf8mb4
COLLATE = utf8mb4_unicode_ci;


-- -----------------------------------------------------
-- Table `comic_reader_db`.`comic_genre`
-- -----------------------------------------------------
CREATE TABLE IF NOT EXISTS `comic_reader_db`.`comic_genre` (
  `comic_id` INT NOT NULL,
  `genre_id` INT NOT NULL,
  PRIMARY KEY (`comic_id`, `genre_id`),
  INDEX `genre_id` (`genre_id` ASC) VISIBLE,
  CONSTRAINT `comic_genre_ibfk_1`
    FOREIGN KEY (`comic_id`)
    REFERENCES `comic_reader_db`.`comics` (`comic_id`)
    ON DELETE CASCADE,
  CONSTRAINT `comic_genre_ibfk_2`
    FOREIGN KEY (`genre_id`)
    REFERENCES `comic_reader_db`.`genres` (`genre_id`)
    ON DELETE CASCADE)
ENGINE = InnoDB
DEFAULT CHARACTER SET = utf8mb4
COLLATE = utf8mb4_unicode_ci;


-- -----------------------------------------------------
-- Table `comic_reader_db`.`roles`
-- -----------------------------------------------------
CREATE TABLE IF NOT EXISTS `comic_reader_db`.`roles` (
  `role_id` INT NOT NULL AUTO_INCREMENT,
  `role_name` VARCHAR(50) NOT NULL,
  PRIMARY KEY (`role_id`),
  UNIQUE INDEX `role_name` (`role_name` ASC) VISIBLE)
ENGINE = InnoDB
AUTO_INCREMENT = 3
DEFAULT CHARACTER SET = utf8mb4
COLLATE = utf8mb4_unicode_ci;


-- -----------------------------------------------------
-- Table `comic_reader_db`.`users`
-- -----------------------------------------------------
CREATE TABLE IF NOT EXISTS `comic_reader_db`.`users` (
  `user_id` INT NOT NULL AUTO_INCREMENT,
  `email` VARCHAR(100) NOT NULL,
  `password_hash` VARCHAR(255) NOT NULL,
  `full_name` VARCHAR(100) CHARACTER SET 'utf8mb4' COLLATE 'utf8mb4_0900_ai_ci' NOT NULL,
  `avatar_url` VARCHAR(500) NULL DEFAULT NULL,
  `role_id` INT NOT NULL DEFAULT '2',
  `created_at` TIMESTAMP NULL DEFAULT CURRENT_TIMESTAMP,
  `updated_at` TIMESTAMP NULL DEFAULT CURRENT_TIMESTAMP ON UPDATE CURRENT_TIMESTAMP,
  PRIMARY KEY (`user_id`),
  UNIQUE INDEX `email` (`email` ASC) VISIBLE,
  INDEX `FKp56c1712k691lhsyewcssf40f` (`role_id` ASC) VISIBLE,
  CONSTRAINT `FKp56c1712k691lhsyewcssf40f`
    FOREIGN KEY (`role_id`)
    REFERENCES `comic_reader_db`.`roles` (`role_id`))
ENGINE = InnoDB
AUTO_INCREMENT = 9
DEFAULT CHARACTER SET = utf8mb4
COLLATE = utf8mb4_unicode_ci;


-- -----------------------------------------------------
-- Table `comic_reader_db`.`comments`
-- -----------------------------------------------------
CREATE TABLE IF NOT EXISTS `comic_reader_db`.`comments` (
  `comment_id` INT NOT NULL AUTO_INCREMENT,
  `user_id` INT NOT NULL,
  `comic_id` INT NOT NULL,
  `content` TEXT NOT NULL,
  `created_at` TIMESTAMP NULL DEFAULT CURRENT_TIMESTAMP,
  PRIMARY KEY (`comment_id`),
  INDEX `user_id` (`user_id` ASC) VISIBLE,
  INDEX `comic_id` (`comic_id` ASC) VISIBLE,
  CONSTRAINT `comments_ibfk_1`
    FOREIGN KEY (`user_id`)
    REFERENCES `comic_reader_db`.`users` (`user_id`)
    ON DELETE CASCADE,
  CONSTRAINT `comments_ibfk_2`
    FOREIGN KEY (`comic_id`)
    REFERENCES `comic_reader_db`.`comics` (`comic_id`)
    ON DELETE CASCADE)
ENGINE = InnoDB
AUTO_INCREMENT = 38
DEFAULT CHARACTER SET = utf8mb4
COLLATE = utf8mb4_unicode_ci;


-- -----------------------------------------------------
-- Table `comic_reader_db`.`follows`
-- -----------------------------------------------------
CREATE TABLE IF NOT EXISTS `comic_reader_db`.`follows` (
  `user_id` INT NOT NULL,
  `comic_id` INT NOT NULL,
  `created_at` TIMESTAMP NULL DEFAULT CURRENT_TIMESTAMP,
  PRIMARY KEY (`user_id`, `comic_id`),
  INDEX `comic_id` (`comic_id` ASC) VISIBLE,
  CONSTRAINT `follows_ibfk_1`
    FOREIGN KEY (`user_id`)
    REFERENCES `comic_reader_db`.`users` (`user_id`)
    ON DELETE CASCADE,
  CONSTRAINT `follows_ibfk_2`
    FOREIGN KEY (`comic_id`)
    REFERENCES `comic_reader_db`.`comics` (`comic_id`)
    ON DELETE CASCADE)
ENGINE = InnoDB
DEFAULT CHARACTER SET = utf8mb4
COLLATE = utf8mb4_unicode_ci;


-- -----------------------------------------------------
-- Table `comic_reader_db`.`password_reset_tokens`
-- -----------------------------------------------------
CREATE TABLE IF NOT EXISTS `comic_reader_db`.`password_reset_tokens` (
  `token_id` INT NOT NULL AUTO_INCREMENT,
  `user_id` INT NOT NULL,
  `token_string` VARCHAR(255) NOT NULL,
  `expiry_date` TIMESTAMP NOT NULL,
  `created_at` TIMESTAMP NULL DEFAULT CURRENT_TIMESTAMP,
  PRIMARY KEY (`token_id`),
  INDEX `user_id` (`user_id` ASC) VISIBLE,
  CONSTRAINT `password_reset_tokens_ibfk_1`
    FOREIGN KEY (`user_id`)
    REFERENCES `comic_reader_db`.`users` (`user_id`)
    ON DELETE CASCADE)
ENGINE = InnoDB
AUTO_INCREMENT = 6
DEFAULT CHARACTER SET = utf8mb4
COLLATE = utf8mb4_unicode_ci;


SET SQL_MODE=@OLD_SQL_MODE;
SET FOREIGN_KEY_CHECKS=@OLD_FOREIGN_KEY_CHECKS;
SET UNIQUE_CHECKS=@OLD_UNIQUE_CHECKS;
