# 1. Config MySQL
spring.datasource.url=jdbc:mysql://localhost:3306/comic_reader_db?useSSL=false&serverTimezone=UTC
spring.datasource.username=${DB_USERNAME:root}
spring.datasource.password=${DB_PASSWORD:your_password_here}
spring.datasource.driver-class-name=com.mysql.cj.jdbc.Driver

spring.jpa.hibernate.ddl-auto=update
spring.jpa.show-sql=true
spring.jpa.properties.hibernate.format_sql=true
spring.jpa.database-platform=org.hibernate.dialect.MySQLDialect

# 3. Config Thymeleaf (Frontend)
spring.thymeleaf.cache=false
spring.thymeleaf.prefix=classpath:/templates/
spring.thymeleaf.suffix=.html

# 4.  (default = 8080)
server.port=8080

# Logging
logging.level.org.springframework=DEBUG

# Email Configuration
spring.mail.host=smtp.gmail.com
spring.mail.port=587
spring.mail.username=${MAIL_USERNAME:your_email@gmail.com}
spring.mail.password=${MAIL_PASSWORD:your_app_password_here}
spring.mail.properties.mail.smtp.auth=true
spring.mail.properties.mail.smtp.starttls.enable=true
spring.mail.properties.mail.smtp.starttls.required=true

#MinIO config
minio.endpoint=${MINIO_ENDPOINT:http://localhost:9000}
minio.url=${MINIO_URL:http://127.0.0.1:9000}
minio.access-key=${MINIO_ACCESS_KEY:minioadmin}
minio.secret-key=${MINIO_SECRET_KEY:minioadmin}
minio.bucket-avatar=avatars
minio.bucket-comic=comics

# File Upload bounds config
spring.servlet.multipart.max-file-size=50MB
spring.servlet.multipart.max-request-size=200MB
server.tomcat.max-swallow-size=-1
server.tomcat.max-http-form-post-size=-1

# Active Profiles
spring.profiles.include=local